-- Mes en el que nacieron más empleados

SELECT EXTRACT(MONTH FROM BIRTH_DATE)
FROM
	(SELECT EXTRACT (MONTH FROM BIRTH_DATE), COUNT(*)
	 FROM EMPLOYEES
	 GROUP BY EXTRACT (MONTH FROM BIRTH_DATE)
	 ORDER BY COUNT(*)) DESC
WHERE ROWNUM = 1;


SELECT TO_CHAR(BIRTH_DATE, MONTH)
FROM EMPLOYEES
GROUP BY TO_CHAR(BIRTH_DATE, MONTH)
HAVING COUNT(*) = (
				SELECT MAX(COUNT(*))
				FROM EMPLOYEES
				GROUP BY TO_CHAR(BIRTH_DATE, MONTH)
				);


-- Seleccionar los 3 departamentos en los que más se cobra.

SELECT ROWNUM, DEPT_NAME, SUMA
FROM (
		SELECT DEPT_NAME, SUM(SALARY) AS SUMA
		FROM SALARIES JOIN EMPLOYEES USING (EMP_NO)
					  JOIN DEPT_EMP USING (EMP_NO)
					  JOIN DEPARTMENTS USING (DEPT_NO)
		GROUP BY DEPT_NAME
		ORDER BY SUM(SALARY) DESC
	)
WHERE ROWNUM <= 3;


