SELECT DEPARTMENT_NAME AS "NOMBRE DEPARTAMENTO", SUM(SALARY) AS "SUMA DE SALARIOS"
FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME;

SELECT DEPARTMENT_NAME AS "NOMBRE DEPARTAMENTO", COUNT(EMPLOYEE_ID) AS "TOTAL EMPLEADOS"
FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME;

SELECT DEPARTMENT_NAME AS "NOMBRE DEPARTAMENTO", COUNT(EMPLOYEE_ID) AS "TOTAL EMPLEADOS"
FROM EMPLOYEES RIGHT JOIN DEPARTMENTS USING (DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME;