SELECT DEPARTMENT_NAME AS "NOMBRE DEPARTAMENTO", SUM(SALARY) AS "SUMA DE SALARIOS"
FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME;

SELECT DEPARTMENT_NAME AS "NOMBRE DEPARTAMENTO", COUNT(EMPLOYEE_ID) AS "TOTAL EMPLEADOS"
FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME;

SELECT DEPARTMENT_NAME AS "NOMBRE DEPARTAMENTO", COUNT(EMPLOYEE_ID) AS "TOTAL EMPLEADOS"
FROM EMPLOYEES RIGHT JOIN DEPARTMENTS USING (DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME;

-- Seleccionar el número de empleados agrupados por el puesto de trabajo que
-- desempeñan

SELECT JOB_TITLE AS "NOMBRE DEL PUESTO", COUNT(EMPLOYEE_ID) AS "TOTAL EMPLEADOS"
FROM EMPLOYEES JOIN JOBS USING (JOB_ID)
GROUP BY JOB_TITLE;

-- Número de empleados agrupados por departamento y puesto de trabajo que 
-- desempeñan.

SELECT DEPARTMENT_NAME AS "NOMBRE DEL DEPARTAMENTO",
       JOB_TITLE AS "PUESTO DE TRABAJO", 
       COUNT(EMPLOYEE_ID) AS "NÚMERO DE EMPLEADOS"
FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID) 
     JOIN JOBS USING (JOB_ID)
GROUP BY DEPARTMENT_NAME, JOB_TITLE
ORDER BY DEPARTMENT_NAME, JOB_TITLE;

-- Seleccionar el nombre del departamento y el salario medio del departamento.

SELECT DEPARTMENT_NAME, AVG(SALARY)
FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME;

-- Seleccionar el nombre del departamento y el salario medio del departamento,
-- con un salario medio MAYOR de 10000

SELECT DEPARTMENT_NAME AS "NOMBRE DEL DEPARTAMENTO", 
       AVG(SALARY) AS "SALARIO MEDIO"
FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME
HAVING AVG(SALARY) >= 10000;

-- Seleccionar el salario medio agrupado por departamento para aquellos 
-- empleados que cobren más de 5000 dolares

SELECT DEPARTMENT_NAME AS "NOMBRE DEL DEPARTAMENTO", 
       AVG(SALARY) AS "SALARIO MEDIO"
FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID)
WHERE SALARY > 5000
GROUP BY DEPARTMENT_NAME;

-- Seleccionar el salario medio agrupado por departamento para aquellos 
-- empleados que cobren más de 5000 dolares en departamentos con salario
-- medio superior a 10000 dolares

SELECT DEPARTMENT_NAME AS "NOMBRE DEL DEPARTAMENTO", 
       AVG(SALARY) AS "SALARIO MEDIO"
FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID)
WHERE SALARY > 5000
GROUP BY DEPARTMENT_NAME
HAVING AVG(SALARY) >= 10000;

-- Contar los empleados que lleven más de 25 años en la empresa

SELECT COUNT(*)
FROM EMPLOYEES
WHERE HIRE_DATE + INTERVAL '25' YEAR < SYSDATE;

-- Salario medio de los empleados agrupado por el número de años que llevan
-- trabajando en la empresa.

SELECT  EXTRACT (YEAR FROM SYSDATE) - EXTRACT (YEAR FROM HIRE_DATE) AS "AÑOS EN LA EMPRESA", 
        AVG (SALARY) AS "SALARIO MEDIO"
FROM EMPLOYEES
GROUP BY EXTRACT (YEAR FROM SYSDATE) - EXTRACT (YEAR FROM HIRE_DATE)
ORDER BY EXTRACT (YEAR FROM SYSDATE) - EXTRACT (YEAR FROM HIRE_DATE) DESC;
--ASÍ NO!! 


SELECT ROUND (MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12, 0),
       AVG (SALARY) AS "SALARIO MEDIO"
FROM EMPLOYEES
GROUP BY ROUND (MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12, 0)
ORDER BY ROUND (MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12, 0) DESC;

-- PARA LOS DE 20 AÑOS O MAS...

SELECT ROUND (MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12, 0),
       AVG (SALARY) AS "SALARIO MEDIO"
FROM EMPLOYEES
WHERE ROUND (MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12, 0) >= 20
GROUP BY ROUND (MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12, 0)
ORDER BY ROUND (MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12, 0) DESC;
